AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for ECS task's Project tata-tata
Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: tata-tataTaskRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: tata-tatalogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: arn:aws:logs:us-east-2:502937263541:log-group:tata-tata:*
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: tata-tataCredentials
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: arn:aws:secretsmanager:us-east-2:502937263541:secret:tata-tata-*
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
Outputs:
  TaskRoleArn:
    Value: !GetAtt TaskRole.Arn
    Description: ARN of Task Role
